### ISSUE TITLE
Support AWS

### ISSUE THREAD

**Issue by alpeshgaglani** [fgimenez/orientdb-cookbook#12]
I'm just starting to use this cookbook to install orientdb on AWS EC2 instances. One of the first issues I ran into is that there are no configuration parameters for AWS_SECRET and AWS_ACCESS_KEY in hazelcast plugin to support EC2 deployment. 
Thanks.

PS: I have never tried to setup orientdb in distributed mode on EC2 before, so I may be missing something?

**Comment by fgimenez** [comment]
@alpeshgaglani thanks a lot for your interest in the project :)

The configuration info that you are refering to should not be put in the cookbook attributes, once the cookbook is converging you have already (created and) accessed the node. Moreover, it would be very difficult to maintain a cookbook with all the cloud providers out there :) 

This information belongs to higher level tools, I think that you should take a look at [1] or [2]

Cheers!

[1] https://github.com/chef/knife-ec2
[2] https://github.com/chef/chef-provisioning

**Comment by alpeshgaglani** [comment]
Hmm.. thanks for the info! I'll take a deeper look at it.

**Comment by muthukumarkubendran** [comment]
@alpeshgaglani - were you able to setup distributed mode in AWS EC2 instance with this cookbook. Please let me know as I'm running into some issues.
