### ISSUE TITLE
Error running testing spec

### ISSUE THREAD

**Issue by mdbelt** [fgimenez/orientdb-cookbook#7]
I'm trying to run "rspec" (version 3.2.0) from the root of cookbook & I'm getting a compilation error on spec/spec_helper.rb indicating the the "<<" is an undefined method.  Specifically the stack trace is:

```
/home/user/direct-chef/cookbooks/orient-db-MDB-Github-Fork/spec/spec_helper.rb:13:in `<top (required)>': undefined method `<<' for {}:Hash (NoMethodError)
        from /home/user/direct-chef/cookbooks/orient-db-MDB-Github-Fork/spec/configuration_spec.rb:1:in `require_relative'
        from /home/user/direct-chef/cookbooks/orient-db-MDB-Github-Fork/spec/configuration_spec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `load'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `each'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:97:in `setup'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:85:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
        from /usr/local/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
        from /usr/local/bin/rspec:23:in `load'
        from /usr/local/bin/rspec:23:in `<main>'
```

Is running rspec the correct way to test this cookbook?  Do you know of an alternate way of doing the intended function that will compile?

**Comment by mdbelt** [comment]
I'm continuing to look around on my end as I have a feeling I've not installed something correctly, but if you've seen this error before any hints would be greatly appreciated.

**Comment by mdbelt** [comment]
Update:  If I comment out line 13 of spec_helper.rb & run "bundle exec rspec" the test passes.  What are the ramifications of removing?

**Comment by fgimenez** [comment]
I think that strainer should be removed from here, with the latest versions of the gems, specially berkshelf, the tests could be run with a Rakefile like this [1]. I'll try to find time to update this, if you are interested do not hesitate to try :)

[1] https://github.com/stackforge/cookbook-openstack-object-storage/blob/master/Rakefile

**Comment by mdbelt** [comment]
I'm hitting obstacles converting from Strainer to Rake.  I can get it to run beautifully locally, but it fails on Travis-CI when it tries to build.  1)  It can't run the knife cookbook test command as Travis-CI doesn't have any knife.rb configuration information.  2)  If I skip that & try & just run the spec I'm getting exceptions as well.

I suspect the project linked above isn't utilizing Travis-CI & that may be why they're getting away with Rake.

**Comment by fgimenez** [comment]
I've uploaded a new version with all the dependencies up to date and with strainer removed, let me know if it works for you

Cheers!

**Comment by mdbelt** [comment]
Excellent.  Thanks.  I see what I did wrong.  I fixed the Readme file to reflect the removal of strainer & will create a PR.  Closing this out thanks.
